import MeetupDetail from "../components/meetups/MeetupDetail";

// This function is needed when you use "getStaticProps" for a dynamic page (like this one)
// It will make Nextjs pre-generate the page for all the needed values during the build process
export async function getStaticPaths() {
  return {
    paths: [
      // The values specified in this array will be available later
      // at the "context" object inside getStaticProps function.

      // In most cases, these values are dynamically generated by fetching data from a API/Database
      {
        params: { meetupId: "m1" },
      },
      {
        params: { meetupId: "m2" },
      },
    ],
    // This indicates if the values inside the "paths" prop contemplates
    // all the needed scenarios; If set to true, Nextjs will try to generate dynamically
    // for the incoming unexpected values
    fallback: false,
  };
}

export async function getStaticProps(context) {
  const { meetupId } = context.params;

  // Here you should use de "meetup" to fetch the meetup details from an API or database

  return {
    props: {
      id: meetupId,
      title: "Prague Vuejs Meetup",
      image:
        "http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcRtDk1qH7TEFjzO9UvReZt-FIGe4E3zOQKCDSS_gCOrEj1oVPytahfV2pW8rMeWUOuv",
      address: "Some Street 5, 123 - Prague, Czech Republic",
      description: "Sample description",
    },
  };
}

export default function MeetupDetails(props) {
  return (
    <MeetupDetail
      title={props.title}
      description={props.description}
      image={props.image}
      address={props.address}
    />
  );
}
